name: 🚀 Run SMSBoom in Action
on:  
  schedule:
   - cron: "0 0 * * *"
   - cron: "0 6 * * *"  
   - cron: "0 12 * * *"
   - cron: "0 18 * * *"

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 签出项目代码
      - uses: actions/checkout@v3
      # 设置 py3.8 环境
      - name: 🚀 Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      
      - name: 🚀 Run SMSBoom Script
        # 此处可以自定义命令行运行参数.替换手机号
        run: |
          pip3 install -r requirements.txt
          python3 smsboom.py run -p ${{ secrets.NUMBER }} -t 32
